# Pytorch Tensor Functions

### Exploring tensors in Pytorch

#### An short introduction about PyTorch and about the chosen functions. 
- torch.Tensor.item() 
- torch.as_strided(input, size, stride, storage_offset=0) → Tensor
- torch.baddbmm(input, batch1, batch2, *, beta=1, alpha=1, out=None) → Tensor
- torch.bincount(input, weights=None, minlength=0) → Tensor
- torch.clamp(input, min, max, out=None) → Tensor

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.Tensor.item() 

Used to get a number(integer or float) from a tensor containing single value

In [5]:
# Example 1 - working
a = torch.tensor([[1]])
a.item()

1

In [9]:
# Example 2 - working
b = torch.tensor([[2.59019]], dtype=torch.float)
c = torch.tensor([[2.59019]], dtype=torch.double)
print(b.item())
c.item()

2.5901899337768555


2.59019

In [1]:
# Example 3 - breaking
d = torch.tensor([[1, 2], [3, 4]])
d.item()

NameError: name 'torch' is not defined

Here we have illustrated that item() function breaks for tensor with any other dimension than 1*1

Use this function when there is a need to read the value (number) from a 1,1 tensor

## Function 2 - torch.as_strided(input, size, stride, storage_offset=0)

This function is used to view existing tensor as a tensor of given size by re-arranging input tensor data by taking 1st argument as input tensor data, second argument as the output matrix dimensions, third argumend has a tuple (let's say (a,b)) which specifies the value at 1st element of next row in an output m,n matrix is given by moving a times from 1st element of 1st row and value of next element in a row of output matrix is given by moving b times from existing element in input matrix. Thus, first 1st column elements in output matrix are contructed by moving "a" times from 1st element in input matrix and for each row next element is given by moving b times in input matrix for corresponding element in input matrix.  

In [3]:
# Example 1 - working
x = torch.randn(3, 3)
print(x)
t = torch.as_strided(x, (2, 2), (1, 2))
t


tensor([[ 2.5491, -1.1397,  1.9218],
        [-0.3671,  1.1454,  0.1861],
        [-0.0153,  2.2154,  0.8601]])


tensor([[ 2.5491,  1.9218],
        [-1.1397, -0.3671]])

In [9]:
# Example 2 - working
u = torch.as_strided(x, (3, 2), (2, 2), 1)
u

tensor([[-1.1397, -0.3671],
        [-0.3671,  0.1861],
        [ 0.1861,  2.2154]])

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
v = torch.as_strided(x, (5, 2), (3, 2), 0)
v

RuntimeError: setStorage: sizes [5, 2], strides [3, 2], and storage offset 0 requiring a storage size of 15 are out of bounds for storage with numel 9

Example 3 breaks because to construct 5,2 matrix with strides 2,2 with offset 0 requires an input matrix of size 5*3 = 15 which is not in range of our given matrix of size 3*3 = 9.

This function is used when we want to view our input matrix in different dimensions with striding across elements and ouput matrix size not exceeding, total size of input matrix as specified in explanation of example 3.

## Function 3 - torch.baddbmm(input, batch1, batch2, *, beta=1, alpha=1, out=None) → Tensor

Performs a batch matrix-matrix product of matrices in batch1 and batch2. input is added to the final result.

batch1 and batch2 must be 3-D tensors each containing the same number of matrices, and complying with matrix multiplication laws. So if batch1 is of size (b, n, m), batch2 has to be of size (b, m , p) and output will be of size (b, n, p)  given input is also of size (b, n, p), complying with matix addition laws.



In [10]:
# Example 1 - working
M = torch.randn(10, 3, 5)
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
torch.baddbmm(M, batch1, batch2).size()

torch.Size([10, 3, 5])

In [17]:
# Example 2 - working
inputMatrix = torch.randn(10, 3, 2)
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 2)
torch.baddbmm(inputMatrix, batch1, batch2,beta = 1, alpha =1, out = None).size()

torch.Size([10, 3, 2])

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
inputMatrix = torch.randn(10, 3, 2)
batch1 = torch.randn(10, 3, 5)
batch2 = torch.randn(10, 4, 2)
torch.baddbmm(inputMatrix, batch1, batch2,beta = 1, alpha =1, out = None).size()

RuntimeError: Expected tensor to have size 5 at dimension 1, but got size 4 for argument #2 'batch2' (while checking arguments for baddbmm)

Example 3 doesn't  have compliance with matrix multiplication of batch1 and batch2 tensors

This function is used to perform weighted tensor multiplication and adding this to a tensor of same dimensions. 

## Function 4 - torch.bincount(input, weights=None, minlength=0) → Tensor

Add some explanations

In [3]:
# Example 1 - working
inputs = torch.tensor([1,2,3,4,5,6,7,8,9]) # creating a 1-d tensor
torch.bincount(inputs, weights=None, minlength=0)

tensor([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [2]:
# Example 2 - working
inputs = torch.tensor([1,2,3,4,8,8,8,8,4]) # creating a 1-d tensor
x = torch.tensor([ 0.0000,  0.2500,  0.5000,  0.7500,  1.0000, 1.2500, 1.5000, 1.7500, 2.0000])
inputs.bincount(x) #Attaching weights and calculating total weights for each value

tensor([0.0000, 0.0000, 0.2500, 0.5000, 2.7500, 0.0000, 0.0000, 0.0000, 5.5000])

In [2]:
# Example 3 - breaking (to illustrate when it breaks)
inputs = torch.tensor([1,2,3,4,8,8,8,8,4,5]) # creating a 1-d tensor
x = torch.tensor([ 0.0000,  0.2500,  0.5000,  0.7500,  1.0000, 1.2500, 1.5000, 1.7500, 2.0000])
inputs.bincount(x)

RuntimeError: input and weights should have the same length

Example 3 doesn't work as the weights tensor length is not equal to the 1-d tensor length

bincount function is used to get the number of times non-negative values in a 1-d tensor are repeated, the values arranged from 0 to the highest value in the input tensor and the bincount output is a tensor with length equal to the highest value in input tensor + 1 (as the repeat count starts with 0). This is also used to calculate the total weights attached to each value in the input tensor as illustrated in example 2 above.

## Function 5 - torch.clamp(input, min, max, out=None) → Tensor

Clamp all elements in input into the range [ min, max ] and returns a resulting tensor

In [14]:
# Example 1 - working
x = torch.tensor([-1.7120,  0.1734, -0.0478, -0.0922]) 
torch.clamp(x, min=-0.5, max=0.5)

tensor([-0.5000,  0.1734, -0.0478, -0.0922])

In [35]:
# Example 2 - working
x = torch.tensor([1,  0, 0, 2.0922], dtype=torch.uint8) 
torch.clamp(x, min=1, out=None)

tensor([1, 1, 1, 2], dtype=torch.uint8)

In [44]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.tensor([1,  0, 0, 2], dtype=torch.uint8) 
torch.clamp(x, min=-1.0, out=None)

RuntimeError: value cannot be converted to type uint8_t without overflow: -1

Example 3 fails because, if input is of type FloatTensor or DoubleTensor, value should be a real number, otherwise it should be an integer.

Use clamp function when upper bound and lower bound values in a tensor needs to be fixed

## Conclusion

It was great exploring five functions from the pytorch tensor functions documentation site. Next its time to analyze other ways this functions would fail as illustrated in the example 3 section for each function. 

## Reference Links

* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* Starter template: https://jovian.ml/aakashns/01-tensor-operations
* Markdown documentation for `formatting jupyter notebook cells`: https://commonmark.org/help/

In [6]:
!pip install jovian --upgrade --quiet

In [7]:
import jovian

In [8]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nirmaldeveloper-net/01-tensor-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/nirmaldeveloper-net/01-tensor-operations


'https://jovian.ml/nirmaldeveloper-net/01-tensor-operations'